### ISSUE TITLE
undefined reference to `__nop'

### ISSUE THREAD

**Issue by MarkEvens** [nimaltd/HX711#4]
in function `hx711_delay_us':
undefined reference to `__nop'

I have put this lib in stm32 project Drivers folder and given path properly

Having this issue can guide me on what I am doing wrong

**Comment by Gocql022** [comment]
My English no so good, please translate the following text, I think it may help you(Chinese to English).
undefined reference to __nop'意味着没有定义__nop()函数，我今天也遇到了这个问题，去网上查了下这个函数的含义，得知这是一个什么都不做只会延时（时间极其短暂）的函数，因此只需在引用了__nop()的文件上面如此定义这个函数：
void  __nop()
{
 ;
}
 这样一个__nop()函数就定义好了，希望能帮到你😊

**Comment by M-S-10** [comment]
__NOP() with an undefined reference is due to a missing header file.

- The __NOP() function is defined in the CMSIS (Cortex Microcontroller Software Interface Standard) library, specifically in core_cm4.h for Cortex-M4

- Typically, including stm32f4xx.h should work for STM32F4 series

- f the CMSIS library is properly included, the __NOP() macro should work without additional configuration

- As a last resort, you can use inline assembly if __NOP() is unavailable: **`__asm("NOP");`**

**Comment by M-S-10** [comment]
@nimaltd You may close this issue. Thanks

**Comment by hamidrajabi** [comment]
@M-S-10 replacing ```__NOP()``` with ```__asm("NOP")``` works for stm32f0.
Thanks.
